import type { Context } from '@deepseek-ai/cordis';
import type { InventoryContext, SessionSource, JobOwner } from './host-types.js';
import type { OsProcess, ProcessScan, Inventory } from './wire.js';
export declare const inject: string[];
export declare const SCAN = "$ErrorActionPreference = 'Stop'\n$rootPids = @()\n$processes = @(Get-CimInstance Win32_Process -Property ProcessId,ParentProcessId,CreationDate,Name,ExecutablePath,CommandLine | ForEach-Object {\n  @{ pid = $_.ProcessId; parent = $_.ParentProcessId; started = $_.CreationDate.ToUniversalTime().Ticks.ToString(); name = $_.Name; path = $_.ExecutablePath; command = $_.CommandLine }\n})\n$listeners = @(Get-NetTCPConnection -State Listen | ForEach-Object {\n  @{ pid = $_.OwningProcess; address = $_.LocalAddress; port = $_.LocalPort }\n})\n$owners = @($listeners | ForEach-Object { $_.pid } | Select-Object -Unique)\nforeach ($entry in $processes) {\n  if ($entry.pid -in $owners -or $entry.pid -in $rootPids) {\n    try { $entry.started = (Get-Process -Id $entry.pid -ErrorAction Stop).StartTime.ToUniversalTime().Ticks.ToString() }\n    catch { $entry.started = $null }\n  }\n}\nConvertTo-Json -InputObject @{ processes = $processes; listeners = $listeners } -Compress -Depth 4";
export declare const KILL = "$ErrorActionPreference = 'Stop'\nAdd-Type -TypeDefinition @'\nusing System;\nusing System.Runtime.InteropServices;\npublic static class TaskManagerStop {\n  [DllImport(\"kernel32.dll\", SetLastError=true)] public static extern IntPtr OpenProcess(uint access, bool inherit, int pid);\n  [DllImport(\"kernel32.dll\", SetLastError=true)] public static extern bool GetProcessTimes(IntPtr handle, out long created, out long exited, out long kernel, out long user);\n  [DllImport(\"kernel32.dll\", SetLastError=true)] public static extern bool TerminateProcess(IntPtr handle, uint exitCode);\n  [DllImport(\"kernel32.dll\")] public static extern uint WaitForSingleObject(IntPtr handle, uint milliseconds);\n  [DllImport(\"kernel32.dll\")] public static extern bool CloseHandle(IntPtr handle);\n}\n'@\n$handle = [TaskManagerStop]::OpenProcess(0x101001, $false, __PID__)\nif ($handle -eq [IntPtr]::Zero) { throw 'Prozess nicht mehr erreichbar' }\ntry {\n  [long]$created = 0; [long]$exited = 0; [long]$kernel = 0; [long]$user = 0\n  if (-not [TaskManagerStop]::GetProcessTimes($handle, [ref]$created, [ref]$exited, [ref]$kernel, [ref]$user)) { throw 'Prozessidentit\u00E4t nicht lesbar' }\n  if ([DateTime]::FromFileTimeUtc($created).Ticks.ToString() -ne '__STARTED__') { throw 'Prozessidentit\u00E4t hat sich ge\u00E4ndert' }\n  if (-not [TaskManagerStop]::TerminateProcess($handle, 1)) { throw 'Prozess konnte nicht beendet werden' }\n  if ([TaskManagerStop]::WaitForSingleObject($handle, 2000) -ne 0) { throw 'Prozessende nicht best\u00E4tigt' }\n} finally { [void][TaskManagerStop]::CloseHandle($handle) }";
export declare function workspaceHint<T extends {
    path: string;
}>(process: Pick<OsProcess, 'path' | 'command'>, workspaces: readonly T[]): T | undefined;
export declare function protectedProcess(process: OsProcess | undefined, byPid: ReadonlyMap<number, OsProcess>, self?: number): boolean;
export declare function jobForProcess(process: OsProcess, byPid: ReadonlyMap<number, OsProcess>, roots: ReadonlyMap<number, JobOwner | null>): JobOwner | undefined;
export declare function inventory(ctx: InventoryContext, sessions: readonly SessionSource[], scan: ProcessScan): Pick<Inventory, 'sessions' | 'processes' | 'scannedAt'>;
export declare function apply(ctx: Context): void;
